### ISSUE TITLE
[Feature Request] Command Line Flags for Automation

### ISSUE THREAD

**Issue by laramy2020** [jbara2002/windows-defender-remover#13]
I would like to see the prompt for both the EXE and BAT files to accept flags
/R (remove)
/N (disable)
/E (enable)
/R (restore point)

and one extra
/NORESTART
Useful for my case in MDT as I can set the task sequence to reboot after the script/exe finishes

Reason being is I use MDT to reinstall computers for people and not everyone I would disable defender for.

So for when i reinstall for my self it would be 
```batch
run.bat /R /NORESTART
```

**Comment by jbara2002** [comment]
it is a good ideea. but it take some time to work for it..

**Comment by laramy2020** [comment]
I have a POC going, issue is I don't have checks for correct flags or too many flags.
one other is the powerrun utility closes as soon as the command is run so i am currently struggling writing something that waits for run2.bat to finish before exiting run.bat

I am trying some sort of goto loop checking for run2.bat using either wmic or tasklist

**Comment by laramy2020** [comment]
I think i got it working on detecting when the longer script (run2.bat) finishes so that the primary call on run.bat wont exit early causing possible issues with automating (eg rebooting too soon)

**Comment by jbara2002** [comment]
The script is having 2 main components.
Run.bat and Run2.bat, so first is running Run.bat. It shows the menu content and principal instructions. Run2.bat is running as SYSTEM User. That's why i put that part in separate files.
The part of command line flags, is a good idea. You can apply to bat, not to exe file. The "EXE FILE" is a compiled SFX, so i need to document that if i can put flags in SFXs. If can do, i'll try to apply your ideea.
