### ISSUE TITLE
Windows 11 quality update failed 0x800f081f

### ISSUE THREAD

**Issue by IRedDragonICY** [jbara2002/windows-defender-remover#17]
Microsoft Defender Antivirus antimalware platform - KB4052623 (Version 4.18.2209.7)

v11 still sometimes have problem with Windows Updates if remove Windows Defender . I can't update  to 22H2 22623.870 Windows Insiders Beta. 
Error Code: 0x800f081f
I'm checking reinstall OS. If only disable option, quality update work as usual.

**Comment by corruptmemory** [comment]
I found that only using the "disable" setting didn't disable the real-time engine, at least not for me.  It appeared in Task Manager and still consumed CPU when stuff was written to disk.

Yeah, I didn't set up a restore point, so the only way to get passed this issue is a fresh install?  Is there any way to reinstall this stuff?  I've spent quite a few hours trying to get things "just right" and it would be nice to not have to start over.

**Comment by jbara2002** [comment]
I'll make workarounds, but first, I will wait one or two updates (security, cumulative) to test the new version of Remover Part.
I will fix that asap.

**Comment by jbara2002** [comment]
About disabler option,  i will try to make persistent because sometimes it not work, and i ran the script again to get work.

**Comment by jbara2002** [comment]
Removing the Defender (by pressing y in Script) will remove Defender from System Package List in Windows. This means, when Microsoft will launch an update which is MpEngine.exe (Defender AntiMalware Svc) is updated its getting an error because is removed. If you want to update Windows, choose the disabler part.

**Comment by bubobih** [comment]
> 

how to retrive if we already remove it?

**Comment by jbara2002** [comment]
by reinstalling Windows, if you don't want to lose data, you can do an system in-place upgrade.
Here is a link for help: 
https://answers.microsoft.com/en-us/windows/forum/all/how-to-perform-an-in-place-upgrade-with-windows-10/7f0b236e-3c6c-4913-9691-c4baa2a6190a

**Comment by bubobih** [comment]
Ohhh crap. U cant make rewerse script maybe...
