### ISSUE TITLE
Firewall Items (context Menu)

### ISSUE THREAD

**Issue by Cabus1982** [jbara2002/windows-defender-remover#29]
Why after running the script to remove Defender these annoying [firewall menus](https://i.ibb.co/31BpWnG/Untitled.png) are created?

**Comment by jbara2002** [comment]
the firewall menus are created because the windows security center are removed and you can't add configure the firewall.
You can config from Control Panel, but are ok.
If you talk about the desktop "Firewall Menu" can be removed in registry editor in
[HKEY_CLASSES_ROOT\DesktopBackground\Shell\Firewall] // remove the firewall key.

**Comment by jbara2002** [comment]
its good... maybe it next version i will make the firewall menu optional.

**Comment by jbara2002** [comment]
made firewall menu optional in the release of v12.0!

**Comment by Cabus1982** [comment]
Great to hear it. By the way, there is a way to run several options at once? Let’s say if I need three listing options write Y,U,G
